"""Generate a JSON Schema for editors from the model and the loaded catalog.

The schema lets an editor (for example VS Code with the YAML extension)
autocomplete fields, controlled values, and document IDs in link fields, and
flag mistakes while typing. It checks one file at a time and is advisory:
`embed-context check` remains the authority, and also enforces the rules
that span files (link ownership, module scope, cycles).

ID lists come from the loaded catalog, so the schema is regenerated by every
`check` and is written to an ignored path rather than committed.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .catalog import Catalog
from .model import FieldSpec, KindSpec, LinkSpec

DEFAULT_PATH = Path(".embed-context") / "schema.json"


def build_schema(catalog: Catalog) -> dict[str, Any]:
    model = catalog.model
    definitions: dict[str, Any] = {}
    for name, kind in model.kinds.items():
        definitions[name] = _kind_schema(catalog, kind)
    for link in model.links.values():
        if not link.local:
            nodes = [node for node in catalog.nodes.values() if link.allows_target(node.kind)]
            definitions[_targets_ref(link)] = _enum(
                [node.address for node in nodes], [f"{node.label} ({node.kind})" for node in nodes]
            )
    top_level = ["module", *model.document_kinds]
    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "EMBED catalog document",
        "description": "Generated from model/ by embed-context; do not edit.",
        "type": "object",
        "required": ["kind"],
        "properties": {
            "kind": _enum(top_level, [model.kinds[k].description or k for k in top_level]),
        },
        "allOf": [
            {"if": {"properties": {"kind": {"const": name}}, "required": ["kind"]}, "then": {"$ref": f"#/definitions/{name}"}}
            for name in top_level
        ],
        "definitions": definitions,
    }


def write_schema(catalog: Catalog, path: Path | None = None) -> Path:
    target = catalog.root / (path or DEFAULT_PATH)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(build_schema(catalog), indent=1) + "\n", encoding="utf-8")
    return target


def _kind_schema(catalog: Catalog, kind: KindSpec) -> dict[str, Any]:
    properties: dict[str, Any] = {}
    required: list[str] = []
    if not kind.entry:
        properties["kind"] = {"const": kind.name}
    for name, spec in kind.fields.items():
        properties[name] = _field_schema(catalog, spec)
        if spec.required:
            required.append(name)
    if kind.name != "module":
        for field, link in catalog.model.links_for(kind.name).items():
            properties[field] = _link_schema(catalog, link)
            if link.required:
                required.append(field)
    schema: dict[str, Any] = {"type": "object", "properties": properties, "additionalProperties": False}
    if kind.description:
        schema["description"] = kind.description
    if required:
        schema["required"] = required
    return schema


def _field_schema(catalog: Catalog, spec: FieldSpec) -> dict[str, Any]:
    if spec.type == "value":
        meanings = catalog.model.values[spec.of]
        single = _enum(list(meanings), list(meanings.values()))
    elif spec.type == "flag":
        single = {"type": "boolean"}
    elif spec.type == "map":
        single = {"type": "object", "additionalProperties": {"type": "string"}}
    elif spec.type == "record" and spec.entry_kind:
        single = {"type": "object", "additionalProperties": {"$ref": f"#/definitions/{spec.entry_kind}"}}
    elif spec.type == "record":
        nested = KindSpec(spec.name, spec.description, True, spec.fields)
        single = _kind_schema_without_links(catalog, nested)
    else:
        single = {"type": "string"}
    schema = {"type": "array", "items": single} if spec.many else single
    if spec.description:
        schema = {**schema, "description": spec.description}
    return schema


def _kind_schema_without_links(catalog: Catalog, kind: KindSpec) -> dict[str, Any]:
    properties = {name: _field_schema(catalog, spec) for name, spec in kind.fields.items()}
    required = [name for name, spec in kind.fields.items() if spec.required]
    schema: dict[str, Any] = {"type": "object", "properties": properties, "additionalProperties": False}
    if required:
        schema["required"] = required
    return schema


def _link_schema(catalog: Catalog, link: LinkSpec) -> dict[str, Any]:
    if link.local:
        target: dict[str, Any] = {"type": "string"}
    else:
        target = {"$ref": f"#/definitions/{_targets_ref(link)}"}
    qualified: dict[str, Any] = {
        "type": "object",
        "properties": {
            "id": target,
            "note": {"type": "string", "description": "Why this link exists."},
            **{name: _field_schema(catalog, spec) for name, spec in link.qualifiers.items()},
        },
        "required": ["id", *[name for name, spec in link.qualifiers.items() if spec.required]],
        "additionalProperties": False,
    }
    has_required_qualifier = any(spec.required for spec in link.qualifiers.values())
    single = qualified if has_required_qualifier else {"anyOf": [target, qualified]}
    schema = {"type": "array", "items": single} if link.many else single
    description = link.description or f"Link; shown on the target as `{link.backlink}`."
    return {**schema, "description": description}


def _targets_ref(link: LinkSpec) -> str:
    """Each link type's target IDs are listed once and referenced from every owner."""
    return f"targets.{link.name}"


def _enum(values: list[str], descriptions: list[str]) -> dict[str, Any]:
    return {"enum": values, "enumDescriptions": descriptions, "markdownEnumDescriptions": descriptions}
